titanic/feedback/urls.py
from django.conf.urls import url
from feedback import views

app_name = 'feedback'

urlpatterns = [
    url(r'^$',views.feedback,name='feedback'),
]

titanic/gre/urls.py
from django.conf.urls import url
from gre import views

app_name = 'gre'

urlpatterns = [
    url(r'^$',views.gre,name='gre_'),
    url(r'^gre_predict',views.gre_predict,name='gre_predict'),
]

titanic/maintainer/urls.py
from django.conf.urls import url
from maintainer import views

app_name = 'maintainer'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^titanic/',views.titanic,name='titanic'),
    url(r'^titanic_predict/',views.titanic_predict,name='titanic_predict'),
    url(r'^aboutus/',views.aboutus,name='aboutus')
]

titanic/titanic/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.contrib.auth import views



urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'',include('maintainer.urls')),
    url(r'gre/',include('gre.urls')),
    url(r'feedback/',include('feedback.urls')),
]

titanic/feedback/models.py
from django.db import models

# Create your models here.
class feedback(models.Model):
    projectname = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    datasetLink = models.URLField(max_length=200,null=True, blank=True)
    optionalLink = models.URLField(max_length=200,null=True, blank=True)
    Email = models.EmailField(max_length=100)
    Contact_number = models.PositiveIntegerField(default=0000000000)

titanic/gre/models.py
from django.db import models

# Create your models here.
class gre(models.Model):
    gre_score = models.FloatField(default=0)
    tofel_score = models.FloatField(default=0)
    university_rating = models.FloatField(default=0)
    sop = models.FloatField(default=0)
    lor = models.FloatField(default=0)
    cgpa = models.FloatField(default=0)
    research = models.IntegerField(default=0)

titanic/maintainer/models.py
from django.db import models

# Create your models here.
class titanic(models.Model):
    passengerid = models.FloatField(default=0)
    passengerclass = models.FloatField(default=0)
    age = models.FloatField(default=0)
    siblings = models.IntegerField(default=0)
    parents = models.IntegerField(default=0)
    fare = models.FloatField(default=0.00)
    female = models.IntegerField(default=0)
    male = models.IntegerField(default=0)
    Cherbourg = models.IntegerField(default=0)
    Queenstown = models.IntegerField(default=0)
    Southampton = models.IntegerField(default=0)

titanic/feedback/forms.py
from django.forms import ModelForm
from feedback.models import feedback

class feedback_form(ModelForm):
    class Meta:
        model = feedback
        fields = '__all__'

titanic/gre/forms.py
from django.forms import ModelForm
from gre.models import gre

class gre_form(ModelForm):
    class Meta:
        model = gre
        fields = '__all__'

titanic/maintainer/forms.py
from django.forms import ModelForm
from maintainer.models import titanic

class titanic_form(ModelForm):
    class Meta:
        model = titanic
        fields = '__all__'

titanic/feedback/views.py
from django.shortcuts import render
from django.http import HttpResponse
from feedback.forms import feedback_form
from maintainer.views import index

# Create your views here.
def feedback(request):
    form = feedback_form()

    if request.method =="POST":
        form = feedback_form(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print("Form validation Failed")

    return render(request,'feedback.html',{'form':form})

titanic/gre/views.py
from django.shortcuts import render
from gre import grefn
from gre.forms import gre_form
import numpy as np

# Create your views here.
grei = []
def gre(request):
    form = gre_form()
    del grei[:]

    if request.method =="POST":
        form = gre_form(request.POST)
        data = request.POST
        gre_score = data.__getitem__('gre_score')
        grei.append(gre_score)
        tofel_score = data.__getitem__('tofel_score')
        grei.append(tofel_score)
        university_rating = data.__getitem__('university_rating')
        grei.append(university_rating)
        sop = data.__getitem__('sop')
        grei.append(sop)
        lor = data.__getitem__('lor')
        grei.append(lor)
        cgpa = data.__getitem__('cgpa')
        grei.append(cgpa)
        research = data.__getitem__('research')
        grei.append(research)


        if form.is_valid():
            form.save(commit=True)
            return gre_predict(request)
        else:
            print("Form validation Failed")
    return render(request,"gre/gre_form.html",{'form':form})


def gre_predict(request):

    inp = grei
    inp = [float(i) for i in inp]
    X_test = np.array([inp])
    val = grefn.predict(inp)
    dictio = {'fin':val}
    return render(request,'gre/gre_predict.html',context=dictio)

titanic/maintainer/views.py
from django.shortcuts import render
from django.http import HttpResponse
from maintainer.forms import titanic_form
from maintainer import pic


import numpy as np
# Create your views here.
#pid = 0,pclass=0,ag = 0,sib=0,par=0,mal=0,fem=0,ec=0,eq=0,es=0
fin = []

def index(request):
     mydict = {'var':"please go ahead and discover at /form guys"}
     return render(request,'index.html',context=mydict)

def aboutus(request):
     mydict = {'var':"please go ahead and discover at /form guys"}
     return render(request,'aboutus.html',context=mydict)

def titanic(request):
    del fin[:]
    form = titanic_form()

    if request.method =="POST":
        form = titanic_form(request.POST)
        data = request.POST
        passengerid = data.__getitem__('passengerid')
        fin.append(passengerid)
        passengerclass = data.__getitem__('passengerclass')
        fin.append(passengerclass)
        age = data.__getitem__('age')
        fin.append(age)
        siblings = data.__getitem__('siblings')
        fin.append(siblings)
        parents = data.__getitem__('parents')
        fin.append(parents)
        fare = data.__getitem__('fare')
        fin.append(fare)
        female = data.__getitem__('female')
        fin.append(female)
        male = data.__getitem__('male')
        fin.append(male)
        c = data.__getitem__('Cherbourg')
        fin.append(c)
        q = data.__getitem__('Queenstown')
        fin.append(q)
        s = data.__getitem__('Southampton')
        fin.append(s)
        if form.is_valid():
            form.save(commit=True)
            return titanic_predict(request)
        else:
            print("Form validation Failed")
    return render(request,"maintainer/titanic_form.html",{'form':form})

def titanic_predict(request):
    li = fin
    li = [float(i) for i in li]
    X_test = np.array([li])
    val = pic.prediction(li)
    dicti = {'fin':val}
    return render(request,'maintainer/titanic_predict.html',context=dicti)

titanic/templates/aboutus.html
{% extends "basic.html" %}
{% block content %}

<div class="jumbotron black_class">
  <h1>TEAM FROM HINDUSTAN UNIVERSITY</h1>
  <p> we are team from the hindustan university chennai ,India</p>
  <p>This was developed to address some of the common questions raising among the students and the society </p>
  <h3>We are ready to solve Your problems</h3>
  <h5>You can fill the form by navigating to the sugesstions page in the navigation bar</h5>
  <p>We even appreciate sending mails to us  at </p>
  <p>bhanupalagati@gmail.com</p>
  <h2>Thank you </h2>
</div>
{% endblock %}

titanic/templates/basic.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- bootsrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- medium style text editor -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <script src="{% static 'js/gre.js' %}"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/gre.css' %}">


    <!-- google fonts  -->
    <link href="https://fonts.googleapis.com/css?family=Black+Ops+One|Lobster|Shrikhand" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">

  </head>
  <body style="overflow-y: scroll; ">
    <nav class="navbar navbar-default navbar-fixed-top techfont custom-navbar">
      <a class="navbar-brand" href="#">Team HITS</a>
      <div class="container">
        <ul class="nav navbar-nav">

          <li><a href="{% url 'maintainer:index' %}">Description</a></li>
          <li><a href="{% url 'maintainer:titanic' %}">The Titanic Problem</a></li>
          <li><a href="{% url 'gre:gre_' %}">Gre</a></li>
          <li><a href="{% url 'maintainer:aboutus' %}">About_Creators</a></li>
          <li><a href="{% url 'feedback:feedback' %}">FeedBack</a></li>
        </ul>
      </nav>
        <div class="content container">
          <div>

            {% block content %}

            {% endblock %}

          </div>
        </div>

</body>
</html>

titanic/templates/feedback.html
{% extends "basic.html" %}

{% block content %}
<div class="container">

  <div class="jumbotron style1">
    <h3>We respect your ideas please go ahead</h3>
    <p>In order to make any project as per your needs you can go ahead and fill out this form thats enough we will approach you as soon as we can </p>
    <h4>Kindly fill out everything for the better understanding and contact</h4>
  </div>
  <div class="row">
    <div class="col-sm-6 col-md-6 col-lg-4" style="font-family: 'Black Ops One', cursive;">
      <form method="post" >
        {# {{ form.as_p }} #}
        <table >
          {% csrf_token %}
            {% for field in form %}
            <tbody>
            <tr>
              <td>
                <label for="{{ field.label }}" style="display:inline-block;vertical-align:middle">{{ field.label_tag }}</label>
              </td>
              <td>
                {{ field }}
              </td>
            </tr>
            {% endfor %}
            </tbody>
          </table>
        {% csrf_token %}
        <input type="submit" class = 'btn btn-primary' value="submit"/>
      </form>
      <br>
      <br>
      <br>
      <p>Thank you for using the service</p>
    </div>

    </div>
  </div>




{% endblock %}

titanic/templates/gre/gre_form.html
{% extends "basic.html" %}

{% block content %}
<div class="container">

  <div class="jumbotron style1">
    <h1>The GRE Problem</h1>
    <h4>This site will predict the chance of getting a seat in the opted University for the masters program based on the gre Gpa and some other useful informations. Hope you get benifit from this</h4>
    <br>
    <p>This was using machine Learning techniques to predict the result. The Random forest with 15 trees is the best fitting algorithm for this process</p>
  </div>
  <div class="row">
    <div class="col-sm-6 col-md-6 col-lg-4" font-family: 'Black Ops One', cursive;">
      <form method="post">
        {# {{ form.as_p }} #}
        <table >
          {% csrf_token %}
            {% for field in form %}
            <tbody>
            <tr>
              <td>
                <label for="{{ field.label }}" style="display:inline-block;vertical-align:middle">{{ field.label_tag }}</label>
              </td>
              <td>
                {{ field }}
              </td>
            </tr>
            {% endfor %}
            </tbody>
          </table>
        {% csrf_token %}
        <input type="submit" class = 'btn btn-primary' value="submit"/>
      </form>
      <br>
      <br>
      <br>
      <p>Thank you for using the service</p>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-8" style="background-color:orange;font-family: 'Black Ops One', cursive;">
      <p>Give Us the GRE Score You Got or Expected Max is 340</p>
      <p>Give Us the TOFFEL Score You Got or Expected Max is 110</p>
      <p>Give the UNIVERSITY RATING you are going to apply that is in the scale of 1 to 5</p>
      <p>Valuate The Statement Of Purpose in the scale of 1 to 5</p>
      <p>Valuate the Letter Of Reference in the scale of 1 to 5/p>
      <p>Enter the CPGA you secured in the Degree Examinations in the scale of 1 to 10</p>
      <p>Enter 1 if you done research 0 if not</p>
    </div>
    </div>
  </div>




{% endblock %}

titanic/templates/gre/gre_predict.html
{% extends "basic.html" %}
{% block content %}
<div class="jumbotron black_class">
  <h1>The GRE Problem Result Page</h1>
  <br>
  <br>

  <h3>{{fin}}</h3>
</div>
{% endblock %}

titanic/templates/index.html
{% extends "basic.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
<div class="jumbotron style1">
  <h2>MACHINE LEARNING MODEL APPLICATION FOR SOLVING THE SMART PROBLEMS</h2>

</div>
<div class="jumbotron" style="font-family: 'Pacifico', cursive;">
    <h3>TITANIC PROBLEM</h3>
    <p>We have collected data from the kaggle data world and we trained the model using almost all the available classifiers and found
     that random forest with 15 trees is performing the best results </p>
    <h4>Accuracy Score</h4>
    <p>Based on the test set results it has been proved that we are getting 86 percent Accuracy score so we can claim that the model is well trained
    and can be launched as a reference model</p>
    <h4>How To Use</h4>
    <p>This is interesting question there are quite lot of ways to get advantage from these sort of applications</p>
    <p>Here we keep in mind that when there is an accident usually few people will miss for them we have to perform search operations
    in that scenario if we gathered all the people's situations we can predict whether the missing person will be still alive or not </p>

</div>

<div class="jumbotron style3">
  <h3>GRE PROBLEM</h3>

  <p>Here we used the collected the data from the kaggle data world and used this to find the regression patterns in the Gre dataset</p>
   <h4>Accuracy Score</h4>
  <p>Because this is a regressor checking the accuracy explicitly won't give us the better result so we tested this manually and validated
  with the results which gave better results nearly 80 percent accuracy it has provided</p>
  <h4>Usage</h4>
  <p>There are lot of people using forums to get there question to be answered that whether they will get a gre seat or not</p>
  <p> So by this site they can provide some information about their marks and the situation they our well trained machine will work out the
  problem and give us the result as a probability of getting seat in the university or not</p>

</div>

{% endblock %}

titanic/templates/maintainer/titanic_form.html
{% extends "basic.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron style1">
    <h1>The Titanic Problem</h1>
    <h4>This site will predict if the person with the given features was in the TITANIC SHIP whether the person was alive or not in the accident</h4>
    <br>
    <p>This was using machine Learning techniques to predict the result. The Random forest with 15 trees is the best fitting algorithm for this process</p>
  </div>
  <div class="row">
      <div class="col-sm-6 col-md-6 col-lg-4" style="background-color:white;font-family: 'Black Ops One', cursive;">
        <form method="post">
          {# {{ form.as_p }} #}
          <table >
            {% csrf_token %}
              {% for field in form %}
              <tbody>
              <tr>
                <td>
                  <label for="{{ field.label }}" style="display:inline-block;vertical-align:middle">{{ field.label_tag }}</label>
                </td>
                <td>
                  {{ field }}
                </td>
              </tr>

              {% endfor %}
              </tbody>
            </table>
          {% csrf_token %}
          <input type="submit" class = 'btn btn-primary' value="submit"/>
        </form>
      </div>
      <div class="col-sm-6 col-md-6 col-lg-8" style="background-color:orange;font-family: 'Black Ops One', cursive;">
        <p>passengerid is the person id that will start from 1 and continue</p>
        <p>passengerclass has 1 = upper 2 = middle 3 = lower</p>
        <p>Age is your wish</p>
        <p>give number of siblings are in the ship along with you</p>
        <p>give the number of parents along with you in the ship</p>
        <p>Fare is the price he or she paid for the ticket those are ranging from 3 to 80</p>
        <p>Mark this as 1 if the person is female</p>
        <p>mark this as 1 if the person is male</p>
        <p>mark this as 1 when the person boarding point is this</p>
        <p>mark this as 1 when the person boarding point is this</p>
        <p>mark this as 1 when the person boarding point is this</p>
      </div>
    </div>

  <h3>Check out the remaining algorithms</h3>
</div>
{% endblock %}

titanic/templates/maintainer/titanic_predict.html
{% extends "basic.html" %}
{% block content %}
<div class="jumbotron black_class">
  <h1>The TITANIC Problem Result Page</h1>
  <br>
  <br>

  <h3>{{fin}}</h3>

</div>
{% endblock %}